name: elise
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - openssl=3.5.0
  - pip=25.1
  - python=3.13.2
  - python_abi=3.13
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - pip:
      - annotated-types==0.7.0
      - blinker==1.9.0
      - brotli==1.1.0
      - cachelib==0.13.0
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - dash==3.0.4
      - dash-bootstrap-components==2.0.2
      - dash-extensions==2.0.4
      - dataclass-wizard==0.35.0
      - dnspython==2.7.0
      - editorconfig==0.17.0
      - flask==3.0.3
      - flask-caching==2.3.1
      - flask-compress==1.17
      - gevent==25.4.2
      - greenlet==3.2.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsbeautifier==1.15.4
      - markupsafe==3.0.2
      - more-itertools==10.7.0
      - mpi4py==4.0.3
      - narwhals==1.36.0
      - nest-asyncio==1.6.0
      - numpy==2.2.5
      - orjson==3.10.16
      - packaging==25.0
      - pandas==2.2.3
      - plotly==5.24.1
      - plotly-resampler==0.10.0
      - procset==1.0
      - psutil==7.0.0
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pymongo==4.12.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - retrying==1.3.4
      - setuptools==79.0.1
      - six==1.17.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tsdownsample==0.1.4.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.0.6
      - zipp==3.21.0
      - zope-event==5.0
      - zope-interface==7.2
      - zstandard==0.23.0
